region                 = "ap-south-1"
vpc_cidr               = "10.10.0.0/16"
azs                    = ["ap-south-1a", "ap-south-1b"]
ecs_cpu                = 256
ecs_memory             = 512
ecs_desired_count      = 1
db_instance_class      = "db.t3.micro"
db_allocated_storage   = 20
db_backup_retention    = 1
db_deletion_protection = false
db_password            = "YOUR_DB_PASSWORD"
